### ISSUE TITLE
Ahh it says it only works in 64-bit

### ISSUE THREAD

**Issue by seungwonpark** [Quod-processing/main#1]
제 컴퓨터가 32bit운영체제라 그런지 main 코드가 실행이 안됩니다.
server 코드는 실행이 잘되는데...

나중에 application export를 하고 나면 상관없을까요? 그냥 Development할때만 문제인가요?

**Comment by mileu32** [comment]
sorry..
but i3 m330 could install 64bit windows!!

**Comment by mileu32** [comment]
어플리케이션 export 나  develop 할때 모두 문제가 됩니다.
